login/urls.py
from django.conf.urls import url
from django.urls import path
from .member_fetch import load_members

from login import views
from . import datatable
from . import uploadfile


# SET THE NAMESPACE!
app_name = 'login'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    #url(r'^login/',include('login.urls'))
    
    path('exammember/', views.Member, name='exammember'),
    path('deletemember/<int:id>', datatable.DeleteMember, name='deletemember'),
    path('editmember/<int:id>', datatable.EditMember, name='editmember'),
    path('updatemember/<int:id>', datatable.UpdateMember, name='updatemember'),
    path('iso/', views.Member1, name='iso'),
    path('asset/', views.Member2, name='asset'),
    path('deleteiso/<int:id>', datatable.DeleteISO, name='deleteiso'),
    path('editiso/<int:id>', datatable.EditISO, name='editiso'),
    path('updateiso/<int:id>', datatable.UpdateISO, name='updateiso'),
    path('deleteasset/<int:id>', datatable.DeleteAsset, name='deleteasset'),
    path('editasset/<int:id>', datatable.EditAsset, name='editasset'),
    path('updateasset/<int:id>', datatable.UpdateAsset, name='updateasset'),
    path('vul/', views.Member3, name='vul'),
    path('vul1/', views.Member_vul, name='vul1'),
    path('editvul1/<int:id>', datatable.EditVul1, name='editvul1'),
    path('updatevul1/<int:id>', datatable.UpdateVul1, name='updatevul1'),
    path('deletevul1/<int:id>', datatable.DeleteVul1, name='deletevul1'),
    path('editvul/<int:id>', datatable.EditVul1, name='editvul'),
    path('updatevul/<int:id>', datatable.UpdateVul, name='updatevul'),
    path('deletevul/<int:id>', datatable.DeleteVul, name='deletevul'),
    path('ciso/', views.Member4, name='ciso'),
    path('editciso/<int:id>', datatable.Editciso, name='editciso'),
    path('updateciso/<int:id>', datatable.Updateciso, name='updateciso'),
    path('deleteciso/<int:id>', datatable.Deleteciso, name='deleteciso'),
    #path('uploadmember/', uploadfile.UploadMemberXls.as_view(), name='uploadmember')
    path('loadmembers/', load_members, name='loadmembers')


]

webapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from login import views
#from apicalls.usercreation import (getExamMembers)

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    #url(r'^login/',include('login.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    #path('exammembers',getExamMembers,name='exammembers'),
    path('member/',include('login.urls'))
]

login/models.py
import email
from email.policy import default
from random import choices
from django.db import models
from django.utils import timezone



# Create your models here.
from unicodedata import name
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from login.choice import status, shift, dcode
#from django.core.validators import MinLengthValidator
#from django.core import validators
#from .validators import (ContactNumberCheck)
# Create your models here.

class UserProfileInfo(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE)
	portfolio_site = models.CharField(max_length=100)
	profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
def __str__(self):
  return self.username

class ExamMember(models.Model):
	departmentid				= models.CharField(max_length=250)
	departmentcode				= models.CharField(max_length=250)
	organisationaname			= models.CharField(max_length=250)
	departmentname				= models.CharField(max_length=250)
	phone_number				= models.CharField(max_length=10,unique=True)
	date						= models.DateField()
	email						= models.EmailField(max_length = 254)
	modificationdate			= models.DateTimeField(auto_now_add=True)
	# username			= models.ForeignKey(User,on_delete=models.CASCADE)

	def __str__(self):
		return self.departmentname

class ISO(models.Model):
	departmentid			= models.CharField(max_length=250)
	departmentcode			= models.CharField(max_length=250)
	organisationaname		= models.CharField(max_length=250)
	departmentname			= models.ForeignKey(ExamMember,on_delete=models.CASCADE)
	nameiso					= models.CharField(max_length=250)
	designation				= models.CharField(max_length=250)
	phone_number			= models.CharField(max_length=10,unique=True)
	date					= models.DateField()
	email					= models.EmailField(max_length = 254)
	status					= models.CharField(max_length=250,choices=status)
	modificationdate		= models.DateTimeField(auto_now_add=True)
	
	def __str__(self):
		return self.departmentname

class CISO(models.Model):
	departmentid			= models.CharField(max_length=250)
	departmentcode			= models.CharField(max_length=250)
	organisationaname		= models.CharField(max_length=250)
	nameciso				= models.CharField(max_length=250)
	designation				= models.CharField(max_length=250)
	phone_number			= models.CharField(max_length=10,unique=True)
	date					= models.DateField()
	email					= models.EmailField(max_length = 254)
	status					= models.CharField(max_length=250,choices=status)
	modificationdate		= models.DateTimeField(auto_now_add=True)
	
	def __str__(self):
		return self.departmentname

class Asset(models.Model):
	organisationaname			= models.CharField(max_length=250)
	departmentname			= models.ForeignKey(ExamMember,on_delete=models.CASCADE)
	url			= models.CharField(max_length=250)
	tnsdcip			= models.CharField(max_length=250)
	nms			= models.CharField(max_length=250,choices=shift)
	nmsdate			= models.DateField()
	assetusage			= models.CharField(max_length=250)
	othersdetails			= models.CharField(max_length=250)
	departmentcontact			= models.CharField(max_length=10,unique=True)
	developer			= models.CharField(max_length=250)
	siem			= models.CharField(max_length=250,choices=shift)
	siemdate			= models.DateField()
	modificationdate			= models.DateTimeField(auto_now_add=True)
	
	def __str__(self):
		return self.name

class Vulnerability(models.Model):
	departmentname			= models.ForeignKey(ExamMember,on_delete=models.CASCADE)
	departmentcode			= models.CharField(max_length=250)
	vulid			= models.CharField(max_length=250)
	vulname			= models.CharField(max_length=250)
	reportby 			= models.CharField(max_length=200)
	reporteddate 			= models.DateField()
	modificationdate			= models.DateField(auto_now_add=True)
	modified_user	= models.ForeignKey(User, on_delete=models.CASCADE)
	active = models.BooleanField(default=True)

	
	def __str__(self):
		return self.vulid		

login/forms.py
from django import forms
from login.models import UserProfileInfo
from django.contrib.auth.models import User
from django.forms import ModelForm
from login.models import (ExamMember, ISO, Asset, Vulnerability, CISO)

class DateInput(forms.DateInput):
    input_type = 'date'

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')

class UserProfileInfoForm(forms.ModelForm):
     class Meta():
         model = UserProfileInfo
         fields = ('portfolio_site','profile_pic')

class ExamMemberForm(ModelForm):
    class Meta:
        model = ExamMember
        fields = "__all__"
        labels = {
            'departmentid': ('departmentid'),
            'departmentcode': ('departmentcode'),
            'organisationaname': ('organisationaname'),
            'departmentname': ('departmentname'),
            'phone_number': ('phone_number'),
            'date': ('date'),
            'email': ('email')


        }
        widgets = {
            'date': DateInput(),
        }

class ISOForm(ModelForm):
    class Meta:
        model = ISO
        fields = "__all__"
        labels = {
            'departmentid': ('departmentid'),		
	        'departmentcode': ('departmentcode'),			
	        'organisationaname': ('organisationaname'),			
	        'departmentname': ('departmentname'),			
	        'nameiso':	('nameiso'),		
	        'designation':	('designation'),		
	        'phone_number':	('phone_number'),		
	        'date':	('date'),		
	        'email': ('email'),			
	        'status': ('status')
        }
        widgets = {
            'date': DateInput(),
        }

class AssetForm(ModelForm):
    class Meta:
        model = Asset
        fields = "__all__"
        labels = {
            'organisationaname': ('organisationaname'),		
	        'departmentname': ('departmentname'),			
	        'url': ('url'),			
	        'tnsdcip': ('tnsdcip'),			
	        'nms':	('nms'),		
	        'nmsdate':	('nmsdate'),		
	        'assetusage':	('assetusage'),		
	        'othersdetails':	('othersdetails'),		
	        'departmentcontact': ('departmentcontact'),			
	        'status': ('status'),
            'departmentcontact': ('departmentcontact'),			
	        'developer': ('developer'),
            'siem': ('siem'),			
	        'siemdate': ('siemdate')
            

        }
        widgets = {
            'date': DateInput(),
            'nmsdate': DateInput(),
            'siemdate': DateInput(),

        }


class VulnerabilityForm(ModelForm):
    class Meta:
        model = Vulnerability
        fields = ['vulid', 'vulname', 'departmentname', 'reportby', 'reporteddate' ]
        labels = {
            'vulid': ('Vulnerability Id'),
            'vulname': ('Vulnerability Name'),
            'departmentname': ('Department Name'),
            'reportby': ('Report By Name'),
            'reporteddate': ('Report Date')
  
        }
        widgets = {
            'reporteddate': DateInput(),
        }  

class CISOForm(ModelForm):
    class Meta:
        model = CISO
        fields = "__all__"
        labels = {
            'departmentid':	('departmentid'),		
	        'departmentcode': ('departmentcode'),			
	        'organisationaname': ('organisationaname'),			
	        'nameciso': ('nameciso'), 			
	        'designation': ('designation'),			
	        'phone_number': ('phone_number'),			
	        'date': ('date'),			
	        'email': ('email'),			
	        'status': ('status')			
	        			
        
        }
        widgets = {
            'date': DateInput(),
        }              

login/views.py
from django.contrib.auth.decorators import login_required
from .models import (ExamMember, ISO, Asset, Vulnerability, CISO)
from .forms import (ExamMemberForm, ISOForm, AssetForm,
                    VulnerabilityForm, CISOForm)
from django.shortcuts import redirect, render
from login.forms import UserForm, UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse


import logging
from django.contrib import messages
logger = logging.getLogger('centmonitoringdebug')

alogger = logging.getLogger('accesslog')

elogger = logging.getLogger('errorlog')

ilogger = logging.getLogger('infolog')


def index(request):
    return render(request, 'login/index.html')


@login_required
def special(request):
    return HttpResponse("You are logged in !")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            # profile = profile_form.save(commit=False)
            # profile.user = user
            # if 'profile_pic' in request.FILES:
            #     print('found it')
            #     profile.profile_pic = request.FILES['profile_pic']
            # profile.save()
            registered = True
        else:
            print(user_form.errors)
    else:
        user_form = UserForm()
    return render(request, 'login/registration.html',
                  {'user_form': user_form,
                           'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        request.session["username"] = username
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return redirect('/member/exammember')
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(
                username, password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'login/login.html', {})


@login_required
def Member(request):
    """
    view of member add and mapping with role
    """
    context = {}
    context['member'] = ExamMember.objects.all()
    if request.method == 'POST':
        memberdet = ExamMemberForm(request.POST)
        if memberdet.is_valid():
            try:
                post = memberdet.save(commit=False)
                post.save()
                return redirect('/member/exammember')
            except Exception in det:
                print(det, '=-')
                return render(request, 'login/exammember.html', context)
        else:
            context['form'] = memberdet
            return render(request, 'login/exammember.html', context)
    else:
        context['form'] = ExamMemberForm()
        return render(request, 'login/exammember.html', context)



@login_required
def Member1(request):
    """
    view of member add and mapping with role
    """
    context = {}
    context['iso'] = ISO.objects.all()
    if request.method == 'POST':
        memberdet1 = ISOForm(request.POST)
        if memberdet1.is_valid():
            try:
                post = memberdet1.save(commit=False)
                post.save()
                return redirect('/member/iso')
            except Exception in det:
                print(det, '=-')
                return render(request, 'login/iso.html', context)
        else:
            context['form'] = memberdet1
            return render(request, 'login/iso.html', context)
    else:
        context['form'] = ISOForm()
        return render(request, 'login/iso.html', context)


@login_required
def Member2(request):
    """
    view of member add and mapping with role
    """
    context = {}
    context['asset'] = Asset.objects.all()
    if request.method == 'POST':
        memberdet2 = AssetForm(request.POST)
        if memberdet2.is_valid():
            try:
                post = memberdet2.save(commit=False)
                post.save()
                return redirect('/member/asset')
            except Exception in det:
                print(det, '=-')
                return render(request, 'login/asset.html', context)
        else:
            context['form'] = memberdet2
            return render(request, 'login/asset.html', context)
    else:
        context['form'] = AssetForm()
        return render(request, 'login/asset.html', context)


@login_required
def Member3(request):
    """
    view of member add and mapping with role
    """
    context = {}
    context['vul'] = Vulnerability.objects.all()
    if request.method == 'POST':
        memberdet3 = VulnerabilityForm(request.POST)
        if memberdet3.is_valid():
            try:
                post = memberdet3.save(commit=False)
                post.modified_user = request.user
                post.save()
                return redirect('/member/vul')
            except Exception in det:
                print(det, '=-')
                return render(request, 'login/vulnerability.html', context)
        else:
            context['form'] = memberdet3
            return render(request, 'login/vulnerability.html', context)
    else:
        context['form'] = VulnerabilityForm()
        return render(request, 'login/vulnerability.html', context)


@login_required
def Member_vul(request):
    """
    view of member add and mapping with role
    """
    context = {}
    context['vul1'] = Vulnerability.objects.all()
    if request.method == 'POST':
        memberdet6 = VulnerabilityForm(request.POST)
        if memberdet6.is_valid():
            try:
                post = memberdet6.save(commit=False)
                post.modified_user = request.user
                post.save()
                return redirect('/member/vul1')
            except Exception in det:
                print(det, '=-')
                return render(request, 'login/vul_report.html', context)
        else:
            context['form'] = memberdet6
            return render(request, 'login/vul_report.html', context)
    else:
        context['form'] = VulnerabilityForm()
        return render(request, 'login/vul_report.html', context)


@login_required
def Member4(request):
    """
    view of member add and mapping with role
    """
    context = {}
    context['ciso'] = CISO.objects.all()
    if request.method == 'POST':
        memberdet4 = CISOForm(request.POST)
        if memberdet4.is_valid():
            try:
                post = memberdet4.save(commit=False)
                post.save()
                return redirect('/member/ciso')
            except Exception in det:
                print(det, '=-')
                return render(request, 'login/ciso.html', context)
        else:
            context['form'] = memberdet4
            return render(request, 'login/ciso.html', context)
    else:
        context['form'] = CISOForm()
        return render(request, 'login/ciso.html', context)

templates/login/asset.html
{% extends "login/base.html" %}
{% block body_block %}
{% load crispy_forms_tags %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js">
<link rel="stylesheet" href="https://code.jquery.com/jquery-3.5.1.js">
<link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js">
<script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js" defer></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<header>
      <h1>Asset Details</h1>
</header>

<form method="POST" class="post-form">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-primary" type="submit" value="Submit">Save</button>

</form>
<div class="table-responsive">
    <!-- <input type="text" id="myInput" placeholder="Search.." title="Type in a name"> -->
    <table id="example" class="table table-striped table-bordered" cellspacing="0">
        <thead>
            <th class="text-center">organisationaname</th>
            <th class="text-center">departmentname</th>
            <th class="text-center">url</th>
            <th class="text-center">tnsdcip</th>
            <th class="text-center">nms</th>
            <th class="text-center">nmsdate</th>
            <th class="text-center">assetusage</th>
            <th class="text-center">othersdetails</th>
            <th class="text-center">departmentcontact</th>
            <th class="text-center">developer</th>
            <th class="text-center">siem</th>
            <th class="text-center">siemdate</th>
            <th class="text-center">Modified</th>
            <th class="text-center">User</th>
            <th class="text-center">Remarks</th>
        </thead>
        <tbody>
            {% for m in asset %}
            <tr>
                <td class="text-center">{{ m.organisationaname }}</td>
                <td class="text-center">{{ m.departmentname }}</td>
                <td class="text-center">{{ m.url }}</td>
                <td class="text-center">{{ m.tnsdcip }}</td>
                <td class="text-center">{{ m.nms }}</td>
                <td class="text-center">{{ m.nmsdate|date:'d-m-y' }}</td>
                <td class="text-center">{{ m.assetusage }}</td>
                <td class="text-center">{{ m.othersdetails }}</td>
                <td class="text-center">{{ m.departmentcontact }}</td>
                <td class="text-center">{{ m.developer }}</td>
                <td class="text-center">{{ m.siem }}</td>
                <td class="text-center">{{ m.siemdate|date:'d-m-y' }}</td>
                <td class="text-center">{{ m.modificationdate }}</td>
                <td class="text-center">{{ request.session.username }}</td>

                <td>
                    <a class="btn btn-warning btn-sm btn-circle" href="/member/editasset/{{m.id}}">Edit</a>
                    <a class="btn btn-sm btn-danger btn-circle" href="/member/deleteasset/{{m.id}}">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <th>organisationaname</th>
                <th>departmentname</th>
                <th>url</th>
                <th>tnsdcip</th>
                <th>nms</th>
                <th>nmsdate</th>
                <th>assetusage</th>
                <th>othersdetails</th>
                <th>departmentcontact</th>
                <th>developer</th>
                <th>siem</th>
                <th>siemdate</th>
                <th>Modified</th>
                <th>User</th>
                <th>Remarks</th>

            </tr>
        </tfoot>
    </table>
</div>
<script>

    // function mySearch() {
    //     var input, filter, table, tr, td, i, txtValue;
    //     input = document.getElementById("myInput");
    //     filter = input.value.toUpperCase();
    //     table = document.getElementById("example");
    //     tr = table.getElementsByTagName("tr");
    //     for (i = 0; i < tr.length; i++) {
    //         td = tr[i].getElementsByTagName("td")[0];
    //         if (td) {
    //             txtValue = td.textContent || td.innerText;
    //             if (txtValue.toUpperCase().indexOf(filter) > -1) {
    //                 tr[i].style.display = "";
    //             } else {
    //                 tr[i].style.display = "none";
    //             }
    //         }
    //     }
    // }
    // $(document).ready(function () {
    //     $("#myInput").on("keyup", function () {
    //         var value = $(this).val().toLowerCase();
    //         $("#myTable tr").filter(function () {
    //             $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    //         });
    //     });
    // });
    $(document).ready(function () {
        // Setup - add a text input to each footer cell
        $('#example tfoot th').each(function () {
            var title = $(this).text();
            $(this).html('<input type="text" placeholder="Search ' + title + '" />');
        });

        // DataTable
        var table = $('#example').DataTable({
            initComplete: function () {
                // Apply the search
                this.api()
                    .columns()
                    .every(function () {
                        var that = this;

                        $('input', this.footer()).on('keyup change clear', function () {
                            if (that.search() !== this.value) {
                                that.search(this.value).draw();
                            }
                        });
                    });
            },
        });
    });
</script>
{% endblock %}

templates/login/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>CSA-TN</title>
    <style>
      ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  font-size: 20px;
  
}

li {
  display: inline;
}
ul li a { 
		padding: 10px; 
		list-style:none; 
	} 
    </style>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <!-- <ul class="nav navbar-nav"> -->

{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">CSA-TN</a></li>
     
          <li><a class="navbar-link" href="{% url 'login:register' %}">REGISTER</a></li>     
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
          <ul>
            <li><a href="/member/exammember">Department</a></li>
            <li><a href="/member/iso">ISO</a></li>
            <li><a href="/member/ciso">CISO</a></li>
            <li><a href="/member/asset">Asset</a></li>
            <li><a href="/member/vul">Vulnerability</a></li>
            <li><a href="/member/vul1">Vulnerability Report</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'login:user_login' %}">LOGIN</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

templates/login/export.html
{% extends "login/base.html" %}
{% block body_block %}
{% load crispy_forms_tags %}

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!-- Datatable Dependency start -->
<link rel="stylesheet" type="text/css"
    href="https://cdn.datatables.net/v/bs4/jszip-2.5.0/dt-1.10.20/b-1.6.1/b-colvis-1.6.1/b-html5-1.6.1/b-print-1.6.1/r-2.2.3/datatables.min.css" />
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script type="text/javascript"
    src="https://cdn.datatables.net/v/bs4/jszip-2.5.0/dt-1.10.20/b-1.6.1/b-colvis-1.6.1/b-html5-1.6.1/b-print-1.6.1/r-2.2.3/datatables.min.js"></script>

<!-- Datatable Dependency end -->


<div class="container">

    <div class="col-md-12">
        <div class="card">

            <div class="card-header">
                <h4>Data Table Export</h4>
                <p>Data table with print, pdf, csv</p>
            </div>
            <form method="POST" class="post-form">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-primary" type="submit" value="Submit">Save</button>
             
             </form>    
            <div class="card-body">

                <table class="table table-bordered table-hover" id="table_id">
                    <thead>
                        <tr>
                            <th class="text-center">Vulnerability Id</th>
                            <th class="text-center">Vulnerability name</th>
                            <th class="text-center">Department Name</th>
                            <th class="text-center">Report By</th>
                            <th class="text-center">Reported Date</th>
                            <th class="text-center">Modified Date</th>
                            <th class="text-center">User</th>
                            <th class="text-center">Remarks</th>

                        </tr>
                    </thead>
                    <tbody>
                        {% for m in vul %}
                        <tr>
                            <td class="text-center">{{ m.vulid }}</td>
                            <td class="text-center">{{ m.vulname }}</td>
                            <td class="text-center">{{ m.departmentname }}</td>
                            <td class="text-center">{{ m.reportby }}</td>
                            <td class="text-center">{{ m.reporteddate|date:'d-m-y' }}</td>
                            <td class="text-center">{{ m.modificationdate }}</td>
                            <td class="text-center">{{ request.session.username }}</td>


                            <td>
                                <a class="btn btn-warning btn-sm btn-circle" href="/member/editvul/{{m.id}}">Edit</a>
                                <a class="btn btn-sm btn-danger btn-circle" href="/member/deletevul/{{m.id}}">Delete</a>
                            </td>
                        </tr>


                        {% endfor %}    
                    </tbody>
                </table>

            </div>

        </div>
    </div>

</div>
<script>
    $(document).ready(function () {
        $('#table_id').DataTable({

            dom: 'Bfrtip',
            responsive: true,
            pageLength: 25,
            // lengthMenu: [0, 5, 10, 20, 50, 100, 200, 500],

            buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print'
            ]

        });
    });
</script>
{% endblock %}

//     $("#id_departmentname").change(function () {
    // 		var url = "{% url 'load_members' %}"  // get the url of the `load_cities` view
    // 		var departmentname = $(this).val();  // get the selected country ID from the HTML input
    // 		var token = "{{csrf_token}}";
    // 		$.ajax({                       // initialize an AJAX request
    // 			type:"POST",
    // 			headers: {
    // 				'X-CSRFToken':"{{csrf_token}}"
    // 			},
    // 			url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
    // 			data: {
    // 				'departmentname': departmentname       // add the country id to the GET parameters
    // 			},
    // 			success: function (data) { // `data` is the return of the `load_cities` view function
                    
    // 				$("#id_departmentname").html(data);
    // 				console.log(data);
    // 			}
    // 		});
    //   });